#https://github.com/marketplace/actions/auto-update

name: autoupdate

on:

  # This will trigger on all pushes to master.

   push:

     branches:

       - master

jobs:

  autoupdate:

    name: autoupdate

    runs-on: ubuntu-18.04

    steps:
    # https://kjaymiller.com/how-i-autoupdate-my-github-readme-using-github-actions-in-5-easy-steps
        - name: Git checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: '0'
        - name: git
          run: |
            git --version
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
        - name: check for changes
          run: git status
        - name: stage changed files
          run: git add .changerc
        - name: commit changed files
          run: git commit -m "Auto updating .changerc"
        - name: fetch from master
          run: git fetch origin master
        - name: push code to master
          run: git push origin HEAD:master
        
        
        - uses: docker://chinthakagodawita/autoupdate-action:v1
        
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            DRY_RUN: "false"
            PR_FILTER: "all"
            MERGE_MSG: "Branch was auto-updated."
            RETRY_COUNT: "5"
            RETRY_SLEEP: "300"
            MERGE_CONFLICT_ACTION: "fail"
