#https://github.com/marketplace/actions/auto-update

name: autoupdate
on:
  # This will trigger on all pushes to master.
   push:
     branches:
       - master

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
    # https://kjaymiller.com/how-i-autoupdate-my-github-readme-using-github-actions-in-5-easy-steps
        - uses: actions/checkout@v2
        - name: pip install pygithub
          run: pip install pygithub
        - name: run ./scripts/resolve_changerc_conflict.py
          run: python resolve_changerc_conflict.py
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
