#https://github.com/marketplace/actions/auto-update

name: autoupdate
on:
  # This will trigger on all pushes to master.
   push:
     branches:
       - master

permissions: write-all

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: '0'
            persist-credentials: false
        - name: git
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
        - name: Set env author
          run: echo "AUTHOR=$(git log -1 --oneline --pretty=tformat:"%an")" >> $GITHUB_ENV
        - name: Set env subject
          run: echo "SUBJECT=$(git log -1 --oneline --pretty=tformat:"%s")" >> $GITHUB_ENV
        - uses: actions/checkout@v2
        - name: run ./.github/scripts/create_changerc.py
          run: python ./.github/scripts/create_changerc.py
        - name: git add .changerc
          run: |
            git checkout master
            git pull
            git add .changerc
            git commit -m "add changerc"
            git push origin HEAD:master -f
        - name: run ./.github/scripts/create_copy_changerc.py
          run: python ./.github/scripts/create_copy_changerc.py
        - name: git add .changerccopy
          run: |
            git checkout master
            git pull
            git add .changerc_copy
            git commit -m "add changerc copy"
            git push origin HEAD:master -f
        - name: git remove changerc
          run: |
            git rm .changerc
            git commit -m "remove changerc copy"
            git push origin HEAD:master -f

